# Beam Search Planting Algorithm Configuration

simulation:
  T: 100                    # Number of turns for final evaluation
  T_placement: 50           # Simulation during placement
  w_short: 0.5              # Weight for short-term growth (turns 1-5)
  w_long: 2.0               # Weight for long-term growth (turns 6-T)

beam:
  width: 5                  # Number of candidate solutions to maintain
  diversity_weight: 0.3     # Weight for diversity bonus (0 = no diversity, 1 = max diversity)
  pruning_threshold: 0.1    # Prune beams with score < best_score * threshold

placement:
  epsilon: 0.0              # Improvement threshold for stopping
  beta: 1.0                 # Weight for plant reward in selection
  nutrient_bonus: 2.0       # Bonus for varieties that balance nutrients
  
geometry:
  grid_samples: 20          # Grid points per dimension for first plant
  angle_samples: 16         # Tangency angles per existing plant
  max_candidates: 100       # Max candidates to evaluate per beam state
  tolerance: 1.0e-6         # Spatial deduplication tolerance
  max_anchor_pairs: 50      # Max pairs of anchors for CCI generation

heuristic:
  lambda_interact: 1.0      # Weight for interaction density in pre-ranking
  lambda_gap: 0.5           # Weight for gap penalty in pre-ranking

debug:
  verbose: false            # Print debug information during placement
  log_candidates: false     # Log candidate generation details


